[workspace]
name = "python-stack"
channels = ["https://prefix.dev/conda-forge"]
platforms = ["osx-arm64"]
preview = ["pixi-build"]

[dependencies]
python = "*"
numpy = "*"
scipy = "*"
ipython = "*"
scikit-learn = { path = "scikit-learn" }
skore ={ path = "skore" }
