[workspace]
name = "python-stack"
channels = ["https://prefix.dev/conda-forge"]
platforms = ["osx-arm64"]
preview = ["pixi-build"]

[dependencies]
python = "*"
ipykernel = "*"
ipython = "*"
jupyterlab = "*"
ninja = "*"
numpy = "*"
scipy = "*"
scikit-learn = { path = "scikit-learn" }
imbalanced-learn = { path = "imbalanced-learn" }
skore = { path = "skore" }
skrub = { path = "skrub" }

[tasks]
