[workspace]
name = "python-stack"
channels = ["https://prefix.dev/conda-forge"]
platforms = ["osx-arm64"]
preview = ["pixi-build"]

[dependencies]
python = "*"
ipykernel = "*"
ipython = "*"
jupyterlab = "*"
ninja = "*"
numpy = "*"
scipy = "*"

[feature.source.dependencies]
scikit-learn = { path = "scikit-learn" }
imbalanced-learn = { path = "imbalanced-learn" }
skore = { path = "skore" }
skore-local-project = { path = "skore-local-project" }
skore-hub-project = { path = "skore-hub-project" }
skrub = { path = "skrub" }

[feature.clone.tasks]
clean-repo-dirs = "rm -rf imbalanced-learn/imbalanced-learn scikit-learn/scikit-learn skore/skore skore-local-project/skore-local-project skrub/skrub"
clone-imbalanced-learn = "git clone git@github.com:scikit-learn-contrib/imbalanced-learn.git imbalanced-learn/imbalanced-learn"
clone-scikit-learn = "git clone git@github.com:scikit-learn/scikit-learn.git scikit-learn/scikit-learn"
clone-skore = "git clone git@github.com:probabl-ai/skore.git skore/skore"
clone-skore-local-project = "git clone git@github.com:probabl-ai/skore.git skore-local-project/skore-local-project"
clone-skore-hub-project = "git clone git@github.com:probabl-ai/skore.git skore-hub-project/skore-hub-project"
clone-skrub = "git clone git@github.com:skrub-data/skrub.git skrub/skrub"
clone-all = { depends-on = ["clean-repo-dirs", "clone-imbalanced-learn", "clone-scikit-learn", "clone-skore", "clone-skore-local-project", "clone-skrub"] }

clean-lock-files = "rm -rf pixi.lock imbalanced-learn/pixi.lock scikit-learn/pixi.lock skore/pixi.lock skore-local-project/pixi.lock skrub/pixi.lock"
update-imbalanced-learn = { cmd = "pixi update", cwd = "imbalanced-learn" }
update-scikit-learn = { cmd = "pixi update", cwd = "scikit-learn" }
update-skore = { cmd = "pixi update", cwd = "skore" }
update-skore-local-project = { cmd = "pixi update", cwd = "skore-local-project" }
update-skore-hub-project = { cmd = "pixi update", cwd = "skore-hub-project" }
update-skrub = { cmd = "pixi update", cwd = "skrub" }
update-all = { depends-on = ["update-imbalanced-learn", "update-scikit-learn", "update-skore", "update-skore-local-project", "update-skrub"] }

[environments]
source = { features = ["source"] }
clone = { features = ["clone"], no-default-feature = true }
