[workspace]
name = "skore"
channels = ["https://prefix.dev/conda-forge"]
platforms = ["osx-arm64"]
preview = ["pixi-build"]

[package]
name = { workspace = true }
authors = ["skore developers"]
description = "Own your data science"
version = "0.11.0.dev0"

[package.build.backend]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
name = "pixi-build-python"
version = "*"

[package.build.config]
noarch = true

[package.build.source]
path = "skore/skore"

[package.build-dependencies]
python = "*"

[package.host-dependencies]
uv = "*"
python = "*"
hatchling = "*"

[package.run-dependencies]
python = "*"
anywidget = "*"
ipywidgets = "*"
joblib = "*"
matplotlib = "*"
numpy = "*"
pandas = "*"
plotly = "*"
rich = "*"
skrub = "*"
seaborn = "*"
skore-local-project = { path = "../skore-local-project" }
scikit-learn = { path = "../scikit-learn" }

[feature.source.dependencies]
scikit-learn = { path = "../scikit-learn" }
skore-local-project = { path = "../skore-local-project" }
skore = { path = "." }

[feature.dev.dependencies]
ipykernel = "*"
ipython = "*"
jupyterlab = "*"

[environments]
dev = { features = ["source", "dev"], no-default-feature = true }