[workspace]
name = "skore"
channels = ["https://prefix.dev/conda-forge"]
platforms = ["osx-arm64"]
preview = ["pixi-build"]

[package]
name = { workspace = true }
authors = ["skore developers"]
description = "Own your data science"
version = "0.11.0.dev0"

[package.build.backend]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
name = "pixi-build-python"
version = "*"

[package.build.config]
noarch = true

[package.build.source]
path = "skore/skore"

[package.build-dependencies]
python = "*"

[package.host-dependencies]
uv = "*"
python = "*"
hatchling = "*"

[package.run-dependencies]
python = "*"
anywidget = "*"
ipywidgets = "*"
joblib = "*"
matplotlib = "*"
numpy = "*"
pandas = "*"
plotly = "*"
rich = "*"
seaborn = "*"
skore-local-project = { path = "../skore-local-project" }
scikit-learn = { path = "../scikit-learn" }
skrub = { path = "../skrub" }


[feature.source.dependencies]
ninja = "*"
scikit-learn = { path = "../scikit-learn" }
skore-local-project = { path = "../skore-local-project" }
skore = { path = "." }

[feature.dev.dependencies]
ipykernel = "*"
ipython = "*"
jupyterlab = "*"

[feature.lint.dependencies]
pre-commit = "*"

[feature.tests.dependencies]
pytest = "*"
pytest-cov = "*"
pytest-order = "*"
pytest-randomly = "*"
pytest-xdist = "*"
xdoctest = "*"
polars = "*"
pyarrow = "*"

[feature.tests.tasks]
tests = { cmd = "pytest -vsl --cov=skore --cov-report=xml --cov-report=term-missing -n auto", cwd = "skore/skore/tests" }

[feature.docs.dependencies]
altair = "*"
numpydoc = "*"
plotly = "*"
pydata-sphinx-theme = "*"
python-kaleido = "*"
sentence-transformers = "*"
sphinx = "*"
sphinx-design = "*"
sphinx-gallery = "*"
sphinx-copybutton = "*"
sphinx-tabs = "*"
sphinx-autosummary-accessors = "*"
xgboost = "*"

[feature.docs.tasks]
docs = { cmd = "make html", cwd = "skore/sphinx" }

[environments]
dev = { features = ["source", "dev", "docs", "lint", "tests"], no-default-feature = true }
