[workspace]
name = "skore-hub-project"
channels = ["https://prefix.dev/conda-forge"]
platforms = ["osx-arm64"]
preview = ["pixi-build"]

[package]
name = { workspace = true }
authors = ["skore developers"]
description = "Own your data science"
version = "0.11.0.dev0"

[package.build.backend]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
name = "pixi-build-python"
version = "*"

[package.build.config]
noarch = true

[package.build.source]
path = "skore-hub-project/skore-hub-project"

[package.build-dependencies]
python = "*"

[package.host-dependencies]
uv = "*"
python = "*"
hatchling = "*"

[package.run-dependencies]
python = "*"
blake3 = "*"
httpx = "*"
joblib = "*"
matplotlib = "*"
pydantic = "*"
rich = "*"
scikit-learn = { path = "../scikit-learn" }
skops = { path = "../skops" }

[feature.source.dependencies]
skore-hub-project = { path = "." }
skops = { path = "../skops" }

[feature.dev.dependencies]
ipykernel = "*"
ipython = "*"
jupyterlab = "*"

[environments]
dev = { features = ["source", "dev"], no-default-feature = true }